# Generated by Django 4.2 on 2024-01-08 13:54

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xjuser',
            name='nickname',
            field=simplepro.components.fields.CharField(blank=True, max_length=200, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='xjuser',
            name='token',
            field=simplepro.components.fields.CharField(max_length=200, null=True, verbose_name='Token'),
        ),
    ]
