# Generated by Django 5.0.1 on 2024-02-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('makaflow', '0004_remove_subscribe_groups_subscribe_sub_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='xjuser',
            name='sub_groups',
            field=models.ManyToManyField(to='makaflow.subgroup', verbose_name='订阅组'),
        ),
    ]
