# Generated by Django 4.2.10 on 2024-02-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xjuser',
            name='sub_groups',
        ),
        migrations.AddField(
            model_name='xjuser',
            name='sub_groups',
            field=models.CharField(blank=True, max_length=128, verbose_name='订阅组'),
        ),
    ]
