# Generated by Django 4.2.10 on 2024-03-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xjuser',
            name='level',
            field=models.IntegerField(default=0, verbose_name='等级'),
        ),
    ]
