# Generated by Django 4.2 on 2024-01-08 14:33

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_xjuser_nickname_xjuser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xjuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='xjuser',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='xjuser',
            name='level',
            field=simplepro.components.fields.CharField(default=0, max_length=256, verbose_name='等级'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xjuser',
            name='uuid',
            field=simplepro.components.fields.CharField(default=123456, max_length=256, verbose_name='uuid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xjuser',
            name='nickname',
            field=simplepro.components.fields.CharField(blank=True, max_length=256, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='xjuser',
            name='token',
            field=simplepro.components.fields.CharField(default=123456, max_length=256, verbose_name='Token'),
            preserve_default=False,
        ),
    ]
