# Generated by Django 5.0.1 on 2024-02-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_xjuser_sub_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(-1, '已删除'), (0, '禁用'), (1, '正常')], default=1, verbose_name='状态')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=256, verbose_name='键名')),
                ('value', models.CharField(max_length=256, verbose_name='值')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置管理',
            },
        ),
    ]
