# Generated by Django 4.2.10 on 2024-02-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_xjuser_sub_groups_xjuser_sub_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='名称'),
        ),
    ]
