# Generated by Django 4.2 on 2024-01-08 14:36

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_xjuser_company_remove_xjuser_phone_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xjuser',
            name='level',
            field=simplepro.components.fields.InputNumberField(max_length=256, verbose_name='等级'),
        ),
    ]
