# Generated by Django 5.0.1 on 2024-02-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(max_length=256, unique=True, verbose_name='键名'),
        ),
    ]
