# Generated by Django 4.2.9 on 2024-01-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0004_alter_xjuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xjuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='xjuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='可以继承这个角色[/组]的所有权限', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='xjuser',
            name='level',
            field=models.IntegerField(verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='xjuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=256, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='xjuser',
            name='status',
            field=models.IntegerField(choices=[(-1, '已删除'), (0, '禁用'), (1, '正常')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='xjuser',
            name='token',
            field=models.CharField(max_length=256, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='xjuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='xjuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='这个用户的特定权限。 按住 Control 键或 Mac 上的 Command 键来选择多项。', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='xjuser',
            name='uuid',
            field=models.CharField(max_length=256, verbose_name='uuid'),
        ),
    ]
