# Generated by Django 4.2.9 on 2024-01-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_xjuser_created_at_alter_xjuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xjuser',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
    ]
