# Generated by Django 4.2.10 on 2024-02-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(-1, '已删除'), (0, '禁用'), (1, '正常')], default=1, verbose_name='状态')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
            ],
            options={
                'verbose_name': '订阅组',
                'verbose_name_plural': '订阅组管理',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(-1, '已删除'), (0, '禁用'), (1, '正常')], default=1, verbose_name='状态')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('rule', models.CharField(max_length=256, verbose_name='正则表达式')),
            ],
            options={
                'verbose_name': '规则',
                'verbose_name_plural': '规则管理',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(-1, '已删除'), (0, '禁用'), (1, '正常')], default=1, verbose_name='状态')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='名称')),
                ('sub_enable', models.BooleanField(default=True, verbose_name='可订阅')),
                ('prefix', models.CharField(blank=True, max_length=256, verbose_name='前缀')),
                ('use_proxy', models.BooleanField(default=True, verbose_name='通过代理')),
                ('sub_url', models.CharField(max_length=256, verbose_name='订阅地址')),
                ('subscription_userinfo', models.CharField(blank=True, max_length=512, verbose_name='订阅信息')),
                ('repl_names', models.JSONField(blank=True, verbose_name='名称替换')),
                ('content', models.TextField(blank=True, verbose_name='订阅内容')),
                ('server_mirr', models.JSONField(blank=True, verbose_name='镜像地址替换')),
                ('sub_groups', models.ManyToManyField(blank=True, to='makaflow.subgroup', verbose_name='订阅组')),
            ],
            options={
                'verbose_name': '订阅',
                'verbose_name_plural': '订阅管理',
            },
        ),
    ]
