# Generated by Django 4.2.9 on 2024-01-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='use_proxy',
            field=models.BooleanField(default=True, verbose_name='通过代理'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='sub_enable',
            field=models.BooleanField(default=True, verbose_name='可订阅'),
        ),
    ]
