# Generated by Django 4.2.11 on 2024-03-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='分支'),
        ),
    ]
