# Generated by Django 4.2.10 on 2024-03-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='version',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='当前版本'),
        ),
    ]
