# Generated by Django 4.2.10 on 2024-02-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_xjuser_sub_groups_xjuser_sub_groups'),
        ('makaflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='sub_groups',
        ),
        migrations.DeleteModel(
            name='SubGroup',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='sub_groups',
            field=models.CharField(blank=True, max_length=512, verbose_name='订阅组'),
        ),
    ]
