# Generated by Django 4.2.11 on 2024-03-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0002_repo_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(-1, '已删除'), (0, '禁用'), (1, '正常')], default=1, verbose_name='状态')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='名字')),
                ('path', models.CharField(blank=True, max_length=256, verbose_name='路径')),
                ('interval', models.IntegerField(default=7200, verbose_name='更新间隔')),
                ('autoupdate', models.BooleanField(default=True, verbose_name='自动更新')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(-1, '已删除'), (0, '禁用'), (1, '正常')], default=1, verbose_name='状态')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='名字')),
                ('nickname', models.CharField(blank=True, max_length=256, null=True, verbose_name='说明')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('type', models.CharField(choices=[('yaml', 'yaml'), ('conf', 'conf'), ('other', 'other')], default='yaml', verbose_name='类型')),
            ],
            options={
                'verbose_name': '模板',
                'verbose_name_plural': '模板管理',
            },
        ),
        migrations.AlterModelOptions(
            name='repo',
            options={'verbose_name': '仓库', 'verbose_name_plural': '仓库下载'},
        ),
    ]
