# Generated by Django 4.2.10 on 2024-03-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0002_alter_repo_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='order',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
    ]
