# Generated by Django 4.2.9 on 2024-01-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0002_subscribe_use_proxy_alter_subscribe_sub_enable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(-1, '已删除'), (0, '禁用'), (1, '正常')], default=1, verbose_name='状态')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='唯一名字')),
                ('rule', models.CharField(max_length=256, verbose_name='正则表达式')),
            ],
            options={
                'verbose_name': '规则',
                'verbose_name_plural': '规则管理',
            },
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='name',
            field=models.CharField(max_length=256, verbose_name='名称'),
        ),
    ]
