# Generated by Django 4.2.9 on 2024-01-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0003_rule_remove_subscribe_nickname_alter_subscribe_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(-1, '已删除'), (0, '禁用'), (1, '正常')], default=1, verbose_name='状态')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('rule', models.CharField(max_length=256, verbose_name='正则表达式')),
            ],
            options={
                'verbose_name': '规则',
                'verbose_name_plural': '规则管理',
            },
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=256, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='content',
            field=models.TextField(blank=True, verbose_name='订阅内容'),
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='node_excludes',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='repl_names',
            field=models.JSONField(blank=True, verbose_name='名称替换'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='server_mirr',
            field=models.JSONField(blank=True, verbose_name='镜像地址替换'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='node_excludes',
            field=models.ManyToManyField(blank=True, null=True, to='makaflow.rule', verbose_name='排除规则'),
        ),
    ]
