# Generated by Django 4.2.11 on 2024-03-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0003_files_template_alter_repo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': '文件', 'verbose_name_plural': '文件下载'},
        ),
        migrations.AddField(
            model_name='files',
            name='url',
            field=models.CharField(default='', max_length=512, verbose_name='地址'),
            preserve_default=False,
        ),
    ]
