# Generated by Django 4.2.10 on 2024-03-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0003_subscribe_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='autoupdate',
            field=models.BooleanField(default=True, verbose_name='自动更新'),
        ),
    ]
