# Generated by Django 4.2.9 on 2024-01-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0004_systemconfig_alter_rule_name_alter_subscribe_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='订阅内容'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='repl_names',
            field=models.JSONField(blank=True, null=True, verbose_name='名称替换'),
        ),
    ]
