# Generated by Django 4.2.11 on 2024-03-08 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('makaflow', '0004_alter_files_options_files_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(-1, '已删除'), (0, '禁用'), (1, '正常')], default=1, verbose_name='状态')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=256, verbose_name='客户端')),
                ('ip', models.GenericIPAddressField(verbose_name='ip')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订阅日志',
                'verbose_name_plural': '订阅日志',
            },
        ),
    ]
