# Generated by Django 4.2.10 on 2024-03-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0005_alter_subscribe_sub_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemConfig',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='autoupdate',
            field=models.BooleanField(default=True, verbose_name='自动更新'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='interval',
            field=models.IntegerField(default=7200, verbose_name='更新间隔'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='interval',
            field=models.IntegerField(default=7200, verbose_name='更新间隔'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='subscription_userinfo',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='订阅信息'),
        ),
    ]
