# Generated by Django 4.2.9 on 2024-01-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0005_alter_subscribe_content_alter_subscribe_repl_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='prefix',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='前缀'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='server_mirr',
            field=models.JSONField(blank=True, null=True, verbose_name='镜像地址替换'),
        ),
    ]
