# Generated by Django 4.2.10 on 2024-03-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0006_delete_systemconfig_subscribe_autoupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='node_excludes',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='节点排除'),
        ),
    ]
