# Generated by Django 4.2.10 on 2024-03-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0007_subscribe_node_excludes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='node_includes',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='节点包含'),
        ),
    ]
