# Generated by Django 4.2.10 on 2024-03-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0008_subscribe_node_includes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='订阅内容'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='node_excludes',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='节点排除'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='node_includes',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='节点包含'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='前缀'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='server_mirr',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='镜像地址替换'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='sub_groups',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='订阅组'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='sub_url',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='订阅地址'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='subscription_userinfo',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='订阅信息'),
        ),
    ]
