# Generated by Django 4.2.10 on 2024-03-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaflow', '0009_alter_subscribe_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='use_proxy',
            field=models.BooleanField(default=False, verbose_name='通过代理'),
        ),
    ]
